/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_fustinoni_pi_hcsr04_Hcsr04SinglePin */

#ifndef _Included_net_fustinoni_pi_hcsr04_Hcsr04SinglePin
#define _Included_net_fustinoni_pi_hcsr04_Hcsr04SinglePin
#ifdef __cplusplus
extern "C" {
#endif
#undef net_fustinoni_pi_hcsr04_Hcsr04SinglePin_VIRGIN
#define net_fustinoni_pi_hcsr04_Hcsr04SinglePin_VIRGIN 0L
#undef net_fustinoni_pi_hcsr04_Hcsr04SinglePin_SCHEDULED
#define net_fustinoni_pi_hcsr04_Hcsr04SinglePin_SCHEDULED 1L
#undef net_fustinoni_pi_hcsr04_Hcsr04SinglePin_EXECUTED
#define net_fustinoni_pi_hcsr04_Hcsr04SinglePin_EXECUTED 2L
#undef net_fustinoni_pi_hcsr04_Hcsr04SinglePin_CANCELLED
#define net_fustinoni_pi_hcsr04_Hcsr04SinglePin_CANCELLED 3L
/*
 * Class:     net_fustinoni_pi_hcsr04_Hcsr04SinglePin
 * Method:    getDistanceNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_fustinoni_pi_hcsr04_Hcsr04SinglePin_getDistanceNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
