/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04 */

#ifndef _Included_net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04
#define _Included_net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04
#ifdef __cplusplus
extern "C" {
#endif
#undef net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_VIRGIN
#define net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_VIRGIN 0L
#undef net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_SCHEDULED
#define net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_SCHEDULED 1L
#undef net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_EXECUTED
#define net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_EXECUTED 2L
#undef net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_CANCELLED
#define net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_CANCELLED 3L
/*
 * Class:     net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04
 * Method:    getDistanceNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_fustinoni_raspberryPi_pi2Go_sensor_Hcsr04_getDistanceNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
